name: Deploy Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure with OIDC
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A05FD2FE83D04C498B02A229DD5D778A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_54DBE47C69D34A8D934DD63ACC5B2ADC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_703173B7D3774462BA88E0C43C6110CA }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: func-youtube-es-dev-01
          package: .
          remote-build: true
          respect-funcignore: true
